# Generated by Django 4.1.3 on 2022-12-04 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersModule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='OPEN', max_length=60),
        ),
    ]
